#!/usr/bin/env bash


if [[ $# -ne 2 ]]; then
    echo "usage: $0 [path to Pl*.dat] [output path]"
    exit 1
fi

if ! [[ $1 =~ Pl..\.dat ]]; then
    echo "filename $1 not formatted correctly"
    echo "argument 1 must be a path to a Pl__.dat file (i.e. PlCa.dat)"
    exit 1
fi

offsets=$(./mreader $1 | grep animoff | sed -e 's/\s*animoff: //' | sort | uniq)
base=$(echo $1 | sed 's/.dat//')

echo $base > $2
for offset in $offsets; do
    offset=$(printf "%08x" 0x$offset)
    echo "processing ${base}AJ.dat -> ${2}_${offset}.txt"
    ./mreader "${base}AJ.dat" -r $offset &>> ${2}_${offset}.txt
done


