#!/usr/bin/env bash

rm -rf website

mkdir -p website/autoanimtables
mkdir -p website/subactions
mkdir -p website/bvh

for x in datfiles/Pl??.dat; do 
    echo $x
    # animations
    mkdir -p website/autoanimtables/$(basename $x .dat)
    ./inspectanim $x website/autoanimtables/$(basename $x .dat)/$(basename $x .dat);
    
    # subactions
    ./mreader $x 2>&1 1> website/subactions/$(basename $x .dat).txt;
done

for x in datfiles/Pl??Nr.dat; do
    # bvh files
    ./mreader $x -j website/bvh/$(basename $x .dat).bvh
done

# convert txt to html
for f in $(find website | grep -e 'txt$'); do
    newf=${f%.txt}.html
    echo "$f -> $newf"
    ansifilter -H -r style.css \
                -m site_assets/colormap \
                -i $f \
                -o $newf
    rm $f
done 


# build html indexes
for f in website website/*/ website/*/*/; do
    index=$(./htmltree.sh $f)
    echo $index > $f/index.html
    cp site_assets/style.css $f
done 

cd website
git init
git add *
git remote add origin git@github.com:Adjective-Object/melee_subaction_unpacker.git
git commit -am "autogenerated site"
git push --force origin master:gh-pages

